<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ProductName>FGTools</ProductName>
		<AssemblyName>$(ProductName)</AssemblyName>
		<Description>Fall Guys level loader by @floyzi102 on Twitter</Description>
		<BepInExId>flz.fgt</BepInExId>
		<Version>1.5.0-pre5</Version>
		<AssemblyVersion>1.4.99.4</AssemblyVersion>
		<FileVersion>$(AssemblyVersion)</FileVersion>
		<Authors>Floyzi</Authors>
		<PackageProjectUrl>https://github.com/floyzi/FGTools</PackageProjectUrl>
		<RepositoryUrl>$(PackageProjectUrl)</RepositoryUrl>
		<Company>Obed Guys Corp.</Company>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<LangVersion>latest</LangVersion>
		<RestoreAdditionalProjectSources>
			https://api.nuget.org/v3/index.json; https://nuget.bepinex.dev/v3/index.json; https://nuget.samboy.dev/v3/index.json
		</RestoreAdditionalProjectSources>
		<RootNamespace>FGTools</RootNamespace>
		<Configurations>DEV;ClosedBeta;PROD</Configurations>
		<Optimize>True</Optimize>
	</PropertyGroup>

	<PropertyGroup>
		<ReleaseDir>$(SolutionDir)Release\</ReleaseDir>
		<OutLibsDir>$(ReleaseDir)Assets\Lib\</OutLibsDir>
		<LibsDir>$(SolutionDir)Misc\Lib\</LibsDir>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\discord_api\discord_api.csproj" />
	</ItemGroup>

	<ItemGroup>
		<AssemblyMetadata Include="BuildDate" Value="$([System.DateTimeOffset]::UtcNow.ToUnixTimeSeconds())" />
		<AssemblyMetadata Include="BuildGuid" Value="$([System.Guid]::NewGuid())" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)' == 'Dev'">
		<AssemblyMetadata Include="DefineConstants" Value="$(DefineConstants)" />
	</ItemGroup>

	<ItemGroup>
		<NAudioCore Include="$(LibsDir)NAudio\NAudio.Asio.dll" />
		<NAudioCore Include="$(LibsDir)NAudio\NAudio.Core.dll" />
		<NAudioCore Include="$(LibsDir)NAudio\NAudio.dll" />
		<NAudioCore Include="$(LibsDir)NAudio\NAudio.Midi.dll" />
		<NAudioCore Include="$(LibsDir)NAudio\NAudio.Wasapi.dll" />
		<NAudioCore Include="$(LibsDir)NAudio\NAudio.WinMM.dll" />
		<DiscordSDK Include="$(LibsDir)discord_game_sdk.dll" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Copy SourceFiles="$(OutputPath)$(AssemblyName).dll" DestinationFolder="$(ReleaseDir)" />
		<Copy SourceFiles="$(OutputPath)$(AssemblyName).pdb" DestinationFolder="$(ReleaseDir)" Condition="Exists('$(OutputPath)$(AssemblyName).pdb')" />
		<Copy SourceFiles="$(OutputPath)$(AssemblyName).deps.json" DestinationFolder="$(ReleaseDir)" Condition="Exists('$(OutputPath)$(AssemblyName).deps.json')" />
		<Copy SourceFiles="$(OutputPath)discord_api.dll" DestinationFolder="$(OutLibsDir)" />
		<Copy SourceFiles="$(OutputPath)discord_api.pdb" DestinationFolder="$(OutLibsDir)" Condition="Exists('$(OutputPath)discord_api.pdb')" />
		<Copy SourceFiles="@(NAudioCore)" DestinationFolder="$(OutLibsDir)" SkipUnchangedFiles="true" />
		<Copy SourceFiles="@(DiscordSDK)" DestinationFolder="$(OutLibsDir)" SkipUnchangedFiles="true" />
	</Target>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Dev|AnyCPU'">
		<DefineConstants>$(DefineConstants);AUDIODEBUG;LAN_MULTIPLAYER</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='ClosedBeta|AnyCPU'">
		<DefineConstants>$(DefineConstants);AUDIODEBUG;</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='PROD|AnyCPU'">
		<DefineConstants>$(DefineConstants);</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.*" IncludeAssets="compile" />
		<PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Assembly-CSharp">
		  <HintPath>..\..\Misc\Lib\FallGuys\Assembly-CSharp.dll</HintPath>
		</Reference>
		<Reference Include="Assembly-CSharp-firstpass">
		  <HintPath>..\..\Misc\Lib\FallGuys\Assembly-CSharp-firstpass.dll</HintPath>
		</Reference>
		<Reference Include="Catapult.Core">
		  <HintPath>..\..\Misc\Lib\FallGuys\Catapult.Core.dll</HintPath>
		</Reference>
		<Reference Include="Catapult.Modules.Items.Protocol">
		  <HintPath>..\..\Misc\Lib\FallGuys\Catapult.Modules.Items.Protocol.dll</HintPath>
		</Reference>
		<Reference Include="Catapult.Protocol">
		  <HintPath>..\..\Misc\Lib\FallGuys\Catapult.Protocol.dll</HintPath>
		</Reference>
		<Reference Include="Catapult.Services.Gateway.Protocol.Client">
		  <HintPath>..\..\Misc\Lib\FallGuys\Catapult.Services.Gateway.Protocol.Client.dll</HintPath>
		</Reference>
		<Reference Include="Catapult.Services.Login.Protocol.Client">
		  <HintPath>..\..\Misc\Lib\FallGuys\Catapult.Services.Login.Protocol.Client.dll</HintPath>
		</Reference>
		<Reference Include="Cinemachine">
		  <HintPath>..\..\Misc\Lib\FallGuys\Cinemachine.dll</HintPath>
		</Reference>
		<Reference Include="CMS_Runtime">
		  <HintPath>..\..\Misc\Lib\FallGuys\CMS_Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Coffee.UIParticle">
		  <HintPath>..\..\Misc\Lib\FallGuys\Coffee.UIParticle.dll</HintPath>
		</Reference>
		<Reference Include="com.Epic.OnlineServices">
		  <HintPath>..\..\Misc\Lib\FallGuys\com.Epic.OnlineServices.dll</HintPath>
		</Reference>
		<Reference Include="com.playeveryware.eos">
		  <HintPath>..\..\Misc\Lib\FallGuys\com.playeveryware.eos.dll</HintPath>
		</Reference>
		<Reference Include="com.playeveryware.eos.core">
		  <HintPath>..\..\Misc\Lib\FallGuys\com.playeveryware.eos.core.dll</HintPath>
		</Reference>
		<Reference Include="DeviceIO">
		  <HintPath>..\..\Misc\Lib\FallGuys\DeviceIO.dll</HintPath>
		</Reference>
		<Reference Include="DOTween">
		  <HintPath>..\..\Misc\Lib\FallGuys\DOTween.dll</HintPath>
		</Reference>
		<Reference Include="DOTween.Modules">
		  <HintPath>..\..\Misc\Lib\FallGuys\DOTween.Modules.dll</HintPath>
		</Reference>
		<Reference Include="EOS.K3S">
		  <HintPath>..\..\Misc\Lib\FallGuys\EOS.K3S.dll</HintPath>
		</Reference>
		<Reference Include="FallGuys.Client.Protocol">
		  <HintPath>..\..\Misc\Lib\FallGuys\FallGuys.Client.Protocol.dll</HintPath>
		</Reference>
		<Reference Include="FallGuys.Common.Debug.Protocol.Client">
		  <HintPath>..\..\Misc\Lib\FallGuys\FallGuys.Common.Debug.Protocol.Client.dll</HintPath>
		</Reference>
		<Reference Include="FallGuys.Common.Targeting.Protocol.Client">
		  <HintPath>..\..\Misc\Lib\FallGuys\FallGuys.Common.Targeting.Protocol.Client.dll</HintPath>
		</Reference>
		<Reference Include="FallGuys.Gateway.Protocol.Client">
		  <HintPath>..\..\Misc\Lib\FallGuys\FallGuys.Gateway.Protocol.Client.dll</HintPath>
		</Reference>
		<Reference Include="FallGuys.GeneratedProtocol">
		  <HintPath>..\..\Misc\Lib\FallGuys\FallGuys.GeneratedProtocol.dll</HintPath>
		</Reference>
		<Reference Include="FallGuys.Level.Protocol.AuthTokens">
		  <HintPath>..\..\Misc\Lib\FallGuys\FallGuys.Level.Protocol.AuthTokens.dll</HintPath>
		</Reference>
		<Reference Include="FallGuys.Lobby.Protocol.Client">
		  <HintPath>..\..\Misc\Lib\FallGuys\FallGuys.Lobby.Protocol.Client.dll</HintPath>
		</Reference>
		<Reference Include="FallGuys.Lobby.Protocol.Common">
		  <HintPath>..\..\Misc\Lib\FallGuys\FallGuys.Lobby.Protocol.Common.dll</HintPath>
		</Reference>
		<Reference Include="FallGuys.Match.Protocol.Client">
		  <HintPath>..\..\Misc\Lib\FallGuys\FallGuys.Match.Protocol.Client.dll</HintPath>
		</Reference>
		<Reference Include="FallGuys.Player.Protocol.Client">
		  <HintPath>..\..\Misc\Lib\FallGuys\FallGuys.Player.Protocol.Client.dll</HintPath>
		</Reference>
		<Reference Include="FallGuys.Scheduling.Config">
		  <HintPath>..\..\Misc\Lib\FallGuys\FallGuys.Scheduling.Config.dll</HintPath>
		</Reference>
		<Reference Include="FallGuys.Scheduling.Resolution">
		  <HintPath>..\..\Misc\Lib\FallGuys\FallGuys.Scheduling.Resolution.dll</HintPath>
		</Reference>
		<Reference Include="FallGuys.Store.Protocol.Client">
		  <HintPath>..\..\Misc\Lib\FallGuys\FallGuys.Store.Protocol.Client.dll</HintPath>
		</Reference>
		<Reference Include="FMODUnity">
		  <HintPath>..\..\Misc\Lib\FallGuys\FMODUnity.dll</HintPath>
		</Reference>
		<Reference Include="FMODUnityResonance">
		  <HintPath>..\..\Misc\Lib\FallGuys\FMODUnityResonance.dll</HintPath>
		</Reference>
		<Reference Include="Hazel">
		  <HintPath>..\..\Misc\Lib\FallGuys\Hazel.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppMono.Security">
		  <HintPath>..\..\Misc\Lib\FallGuys\Il2CppMono.Security.dll</HintPath>
		</Reference>
		<Reference Include="Il2Cppmscorlib">
		  <HintPath>..\..\Misc\Lib\FallGuys\Il2Cppmscorlib.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem">
		  <HintPath>..\..\Misc\Lib\FallGuys\Il2CppSystem.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem.Configuration">
		  <HintPath>..\..\Misc\Lib\FallGuys\Il2CppSystem.Configuration.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem.Core">
		  <HintPath>..\..\Misc\Lib\FallGuys\Il2CppSystem.Core.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem.Data">
		  <HintPath>..\..\Misc\Lib\FallGuys\Il2CppSystem.Data.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem.Drawing">
		  <HintPath>..\..\Misc\Lib\FallGuys\Il2CppSystem.Drawing.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem.Net.Http">
		  <HintPath>..\..\Misc\Lib\FallGuys\Il2CppSystem.Net.Http.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem.Numerics">
		  <HintPath>..\..\Misc\Lib\FallGuys\Il2CppSystem.Numerics.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem.Runtime.Serialization">
		  <HintPath>..\..\Misc\Lib\FallGuys\Il2CppSystem.Runtime.Serialization.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem.Xml">
		  <HintPath>..\..\Misc\Lib\FallGuys\Il2CppSystem.Xml.dll</HintPath>
		</Reference>
		<Reference Include="Il2CppSystem.Xml.Linq">
		  <HintPath>..\..\Misc\Lib\FallGuys\Il2CppSystem.Xml.Linq.dll</HintPath>
		</Reference>
		<Reference Include="io.sentry.unity.runtime">
		  <HintPath>..\..\Misc\Lib\FallGuys\io.sentry.unity.runtime.dll</HintPath>
		</Reference>
		<Reference Include="Mediatonic.Automation.FallGuys">
		  <HintPath>..\..\Misc\Lib\FallGuys\Mediatonic.Automation.FallGuys.dll</HintPath>
		</Reference>
		<Reference Include="Mediatonic.Benchmarking">
		  <HintPath>..\..\Misc\Lib\FallGuys\Mediatonic.Benchmarking.dll</HintPath>
		</Reference>
		<Reference Include="Mediatonic.Catapult.ClientSdk.Runtime">
		  <HintPath>..\..\Misc\Lib\FallGuys\Mediatonic.Catapult.ClientSdk.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Mediatonic.CommandLineUtils">
		  <HintPath>..\..\Misc\Lib\FallGuys\Mediatonic.CommandLineUtils.dll</HintPath>
		</Reference>
		<Reference Include="Mediatonic.ErrorMonitor">
		  <HintPath>..\..\Misc\Lib\FallGuys\Mediatonic.ErrorMonitor.dll</HintPath>
		</Reference>
		<Reference Include="Mediatonic.Pooling">
		  <HintPath>..\..\Misc\Lib\FallGuys\Mediatonic.Pooling.dll</HintPath>
		</Reference>
		<Reference Include="Mediatonic.Strings">
		  <HintPath>..\..\Misc\Lib\FallGuys\Mediatonic.Strings.dll</HintPath>
		</Reference>
		<Reference Include="MiniJson_Runtime">
		  <HintPath>..\..\Misc\Lib\FallGuys\MiniJson_Runtime.dll</HintPath>
		</Reference>
		<Reference Include="MPG.PreInit.Config">
		  <HintPath>..\..\Misc\Lib\FallGuys\MPG.PreInit.Config.dll</HintPath>
		</Reference>
		<Reference Include="MT.FGClient">
		  <HintPath>..\..\Misc\Lib\FallGuys\MT.FGClient.dll</HintPath>
		</Reference>
		<Reference Include="MTLog">
		  <HintPath>..\..\Misc\Lib\FallGuys\MTLog.dll</HintPath>
		</Reference>
		<Reference Include="MTNetwork">
		  <HintPath>..\..\Misc\Lib\FallGuys\MTNetwork.dll</HintPath>
		</Reference>
		<Reference Include="mvvmbindings">
		  <HintPath>..\..\Misc\Lib\FallGuys\mvvmbindings.dll</HintPath>
		</Reference>
		<Reference Include="NAudio">
			<HintPath>$(LibsDir)NAudio\NAudio.dll</HintPath>
		</Reference>
		<Reference Include="NAudio.Asio">
			<HintPath>$(LibsDir)NAudio\NAudio.Asio.dll</HintPath>
		</Reference>
		<Reference Include="NAudio.Core">
			<HintPath>$(LibsDir)NAudio\NAudio.Core.dll</HintPath>
		</Reference>
		<Reference Include="NAudio.Midi">
			<HintPath>$(LibsDir)NAudio\NAudio.Midi.dll</HintPath>
		</Reference>
		<Reference Include="NAudio.Wasapi">
			<HintPath>$(LibsDir)NAudio\NAudio.Wasapi.dll</HintPath>
		</Reference>
		<Reference Include="NAudio.WinMM">
			<HintPath>$(LibsDir)NAudio\NAudio.WinMM.dll</HintPath>
		</Reference>
		<Reference Include="Newtonsoft.Json">
		  <HintPath>..\..\Misc\Lib\FallGuys\Newtonsoft.Json.dll</HintPath>
		</Reference>
		<Reference Include="OEBIF">
		  <HintPath>..\..\Misc\Lib\FallGuys\OEBIF.dll</HintPath>
		</Reference>
		<Reference Include="ParsingUtils_Runtime">
		  <HintPath>..\..\Misc\Lib\FallGuys\ParsingUtils_Runtime.dll</HintPath>
		</Reference>
		<Reference Include="protobuf-net">
		  <HintPath>..\..\Misc\Lib\FallGuys\protobuf-net.dll</HintPath>
		</Reference>
		<Reference Include="RemoteImages">
		  <HintPath>..\..\Misc\Lib\FallGuys\RemoteImages.dll</HintPath>
		</Reference>
		<Reference Include="Rewired_Core">
		  <HintPath>..\..\Misc\Lib\FallGuys\Rewired_Core.dll</HintPath>
		</Reference>
		<Reference Include="Rewired_Windows">
		  <HintPath>..\..\Misc\Lib\FallGuys\Rewired_Windows.dll</HintPath>
		</Reference>
		<Reference Include="Sentry">
		  <HintPath>..\..\Misc\Lib\FallGuys\Sentry.dll</HintPath>
		</Reference>
		<Reference Include="Sentry.Microsoft.Bcl.AsyncInterfaces">
		  <HintPath>..\..\Misc\Lib\FallGuys\Sentry.Microsoft.Bcl.AsyncInterfaces.dll</HintPath>
		</Reference>
		<Reference Include="Sentry.System.Buffers">
		  <HintPath>..\..\Misc\Lib\FallGuys\Sentry.System.Buffers.dll</HintPath>
		</Reference>
		<Reference Include="Sentry.System.Collections.Immutable">
		  <HintPath>..\..\Misc\Lib\FallGuys\Sentry.System.Collections.Immutable.dll</HintPath>
		</Reference>
		<Reference Include="Sentry.System.Memory">
		  <HintPath>..\..\Misc\Lib\FallGuys\Sentry.System.Memory.dll</HintPath>
		</Reference>
		<Reference Include="Sentry.System.Numerics.Vectors">
		  <HintPath>..\..\Misc\Lib\FallGuys\Sentry.System.Numerics.Vectors.dll</HintPath>
		</Reference>
		<Reference Include="Sentry.System.Reflection.Metadata">
		  <HintPath>..\..\Misc\Lib\FallGuys\Sentry.System.Reflection.Metadata.dll</HintPath>
		</Reference>
		<Reference Include="Sentry.System.Runtime.CompilerServices.Unsafe">
		  <HintPath>..\..\Misc\Lib\FallGuys\Sentry.System.Runtime.CompilerServices.Unsafe.dll</HintPath>
		</Reference>
		<Reference Include="Sentry.System.Text.Encodings.Web">
		  <HintPath>..\..\Misc\Lib\FallGuys\Sentry.System.Text.Encodings.Web.dll</HintPath>
		</Reference>
		<Reference Include="Sentry.System.Text.Json">
		  <HintPath>..\..\Misc\Lib\FallGuys\Sentry.System.Text.Json.dll</HintPath>
		</Reference>
		<Reference Include="Sentry.System.Threading.Tasks.Extensions">
		  <HintPath>..\..\Misc\Lib\FallGuys\Sentry.System.Threading.Tasks.Extensions.dll</HintPath>
		</Reference>
		<Reference Include="Sentry.Unity">
		  <HintPath>..\..\Misc\Lib\FallGuys\Sentry.Unity.dll</HintPath>
		</Reference>
		<Reference Include="Sentry.Unity.Native">
		  <HintPath>..\..\Misc\Lib\FallGuys\Sentry.Unity.Native.dll</HintPath>
		</Reference>
		<Reference Include="spine-unity">
		  <HintPath>..\..\Misc\Lib\FallGuys\spine-unity.dll</HintPath>
		</Reference>
		<Reference Include="SplineEditor">
		  <HintPath>..\..\Misc\Lib\FallGuys\SplineEditor.dll</HintPath>
		</Reference>
		<Reference Include="TheMultiplayerGuys.FGCommon">
		  <HintPath>..\..\Misc\Lib\FallGuys\TheMultiplayerGuys.FGCommon.dll</HintPath>
		</Reference>
		<Reference Include="TheMultiplayerGuys.Utility">
		  <HintPath>..\..\Misc\Lib\FallGuys\TheMultiplayerGuys.Utility.dll</HintPath>
		</Reference>
		<Reference Include="TonicSounds">
		  <HintPath>..\..\Misc\Lib\FallGuys\TonicSounds.dll</HintPath>
		</Reference>
		<Reference Include="TonicSoundsFMOD">
		  <HintPath>..\..\Misc\Lib\FallGuys\TonicSoundsFMOD.dll</HintPath>
		</Reference>
		<Reference Include="TonicTools">
		  <HintPath>..\..\Misc\Lib\FallGuys\TonicTools.dll</HintPath>
		</Reference>
		<Reference Include="TouchInputLayoutsGuard">
		  <HintPath>..\..\Misc\Lib\FallGuys\TouchInputLayoutsGuard.dll</HintPath>
		</Reference>
		<Reference Include="TweenTool">
		  <HintPath>..\..\Misc\Lib\FallGuys\TweenTool.dll</HintPath>
		</Reference>
		<Reference Include="UniRx">
		  <HintPath>..\..\Misc\Lib\FallGuys\UniRx.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Addressables">
		  <HintPath>..\..\Misc\Lib\FallGuys\Unity.Addressables.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Burst">
		  <HintPath>..\..\Misc\Lib\FallGuys\Unity.Burst.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Burst.Unsafe">
		  <HintPath>..\..\Misc\Lib\FallGuys\Unity.Burst.Unsafe.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Collections">
		  <HintPath>..\..\Misc\Lib\FallGuys\Unity.Collections.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Collections.LowLevel.ILSupport">
		  <HintPath>..\..\Misc\Lib\FallGuys\Unity.Collections.LowLevel.ILSupport.dll</HintPath>
		</Reference>
		<Reference Include="Unity.InputSystem">
		  <HintPath>..\..\Misc\Lib\FallGuys\Unity.InputSystem.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Localization">
		  <HintPath>..\..\Misc\Lib\FallGuys\Unity.Localization.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Mathematics">
		  <HintPath>..\..\Misc\Lib\FallGuys\Unity.Mathematics.dll</HintPath>
		</Reference>
		<Reference Include="Unity.MemoryProfiler">
		  <HintPath>..\..\Misc\Lib\FallGuys\Unity.MemoryProfiler.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Postprocessing.Runtime">
		  <HintPath>..\..\Misc\Lib\FallGuys\Unity.Postprocessing.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Profiling.Core">
		  <HintPath>..\..\Misc\Lib\FallGuys\Unity.Profiling.Core.dll</HintPath>
		</Reference>
		<Reference Include="Unity.ResourceManager">
		  <HintPath>..\..\Misc\Lib\FallGuys\Unity.ResourceManager.dll</HintPath>
		</Reference>
		<Reference Include="Unity.TextMeshPro">
		  <HintPath>..\..\Misc\Lib\FallGuys\Unity.TextMeshPro.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Timeline">
		  <HintPath>..\..\Misc\Lib\FallGuys\Unity.Timeline.dll</HintPath>
		</Reference>
		<Reference Include="Unity.ucg.QoS">
		  <HintPath>..\..\Misc\Lib\FallGuys\Unity.ucg.QoS.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AccessibilityModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.AccessibilityModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AIModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.AIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AndroidJNIModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.AndroidJNIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AnimationModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.AnimationModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AssetBundleModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.AssetBundleModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.AudioModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.AudioModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ClothModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.ClothModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ClusterInputModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.ClusterInputModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ClusterRendererModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.ClusterRendererModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ContentLoadModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.ContentLoadModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.CoreModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CrashReportingModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.CrashReportingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.DirectorModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.DirectorModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.DSPGraphModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.DSPGraphModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.GameCenterModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.GameCenterModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.GIModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.GIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.GridModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.GridModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.HotReloadModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.HotReloadModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ImageConversionModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.ImageConversionModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.IMGUIModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.IMGUIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.InputLegacyModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.InputLegacyModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.InputModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.InputModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.JSONSerializeModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.JSONSerializeModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.LocalizationModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.LocalizationModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ParticleSystemModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.ParticleSystemModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.PerformanceReportingModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.PerformanceReportingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.Physics2DModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.Physics2DModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.PhysicsModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.PhysicsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ProfilerModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.ProfilerModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.PropertiesModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.PropertiesModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.ScreenCaptureModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.ScreenCaptureModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SharedInternalsModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.SharedInternalsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SpriteMaskModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.SpriteMaskModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SpriteShapeModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.SpriteShapeModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.StreamingModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.StreamingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SubstanceModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.SubstanceModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.SubsystemsModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.SubsystemsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TerrainModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.TerrainModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TerrainPhysicsModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.TerrainPhysicsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TextCoreFontEngineModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.TextCoreFontEngineModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TextCoreTextEngineModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.TextCoreTextEngineModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TextRenderingModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.TextRenderingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TilemapModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.TilemapModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.TLSModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.TLSModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UI">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.UI.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UIElementsModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.UIElementsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UIModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.UIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UmbraModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.UmbraModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityAnalyticsCommonModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.UnityAnalyticsCommonModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityAnalyticsModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.UnityAnalyticsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityConnectModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.UnityConnectModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityCurlModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.UnityCurlModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityTestProtocolModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.UnityTestProtocolModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestAssetBundleModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.UnityWebRequestAssetBundleModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestAudioModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.UnityWebRequestModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestTextureModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.UnityWebRequestTextureModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UnityWebRequestWWWModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.UnityWebRequestWWWModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VehiclesModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.VehiclesModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VFXModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.VFXModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VideoModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.VideoModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VirtualTexturingModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.VirtualTexturingModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.VRModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.VRModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.WindModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.WindModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.XRModule">
		  <HintPath>..\..\Misc\Lib\FallGuys\UnityEngine.XRModule.dll</HintPath>
		</Reference>
		<!--i'm using CUE version for testing, you can remove this if needed-->
		<!--<Reference Include="UniverseLib.BIE.IL2CPP.Interop">
			<HintPath>$(LibsDir)UniverseLib\UniverseLib.BIE.IL2CPP.Interop_CUE.dll</HintPath>
		</Reference>-->
		<Reference Include="UniverseLib.BIE.IL2CPP.Interop">
			<HintPath>$(LibsDir)UniverseLib\UniverseLib.BIE.IL2CPP.Interop.dll</HintPath>
		</Reference>
		<Reference Include="Wushu.AsyncFileIO.Runtime">
		  <HintPath>..\..\Misc\Lib\FallGuys\Wushu.AsyncFileIO.Runtime.dll</HintPath>
		</Reference>
		<Reference Include="Wushu.LevelEditor.Runtime">
		  <HintPath>..\..\Misc\Lib\FallGuys\Wushu.LevelEditor.Runtime.dll</HintPath>
		  <Aliases>wle</Aliases>
		</Reference>
	</ItemGroup>

	<Import Project="FLZ_BuildTargets.targets" />
	<ItemGroup>
		<None Update="FLZ_BuildTargets.targets" Visible="false" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="__Generated">
	    <HintPath>..\..\Misc\Lib\FallGuys\__Generated.dll</HintPath>
	  </Reference>
	</ItemGroup>
</Project>
